# Generated by Django 2.0.2 on 2018-02-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
