# Generated by Django 2.0.2 on 2018-02-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0002_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('game', 'ゲーム'), ('fashion', 'ファッション')], max_length=255, null=True),
        ),
    ]
