# Generated by Django 2.0.2 on 2018-02-26 09:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0003_auto_20180226_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='labels',
            field=django_mysql.models.ListTextField(models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
    ]
